"""Standalone solution generated by the local Agent.

Task: B
Strategy: baseline_safe_grid
Estimated sum_radii: 2.166665260667
Estimated score denominator: 2.635990
Diagnostics: {'source': 'safe deterministic grid', 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.1666652606666665, 'score_estimate': 0.8219550380186065, 'boundary_margin': 1.9999999989472883e-09, 'overlap_margin': 1.0000000000287557e-07}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.08333333333333333, 0.1                ],
 [0.25               , 0.1                ],
 [0.4166666666666667 , 0.1                ],
 [0.5833333333333334 , 0.1                ],
 [0.75               , 0.1                ],
 [0.9166666666666666 , 0.1                ],
 [0.08333333333333333, 0.3                ],
 [0.25               , 0.3                ],
 [0.4166666666666667 , 0.3                ],
 [0.5833333333333334 , 0.3                ],
 [0.75               , 0.3                ],
 [0.9166666666666666 , 0.3                ],
 [0.08333333333333333, 0.5                ],
 [0.25               , 0.5                ],
 [0.4166666666666667 , 0.5                ],
 [0.5833333333333334 , 0.5                ],
 [0.75               , 0.5                ],
 [0.9166666666666666 , 0.5                ],
 [0.08333333333333333, 0.7                ],
 [0.25               , 0.7                ],
 [0.4166666666666667 , 0.7                ],
 [0.5833333333333334 , 0.7                ],
 [0.75               , 0.7                ],
 [0.9166666666666666 , 0.7                ],
 [0.08333333333333333, 0.9                ],
 [0.25               , 0.9                ]], dtype=float)
RADII = np.array([0.08333323333333333, 0.08333333333333336, 0.08333323333333333, 0.08333333333333336, 0.08333323333333327,
 0.08333323333333337, 0.08333333133333333, 0.08333323333333337, 0.08333333333333331, 0.08333323333333337,
 0.08333333333333326, 0.08333323333333337, 0.08333333133333333, 0.08333323333333337, 0.08333333333333331,
 0.08333323333333337, 0.08333333333333326, 0.08333323333333337, 0.08333333133333333, 0.08333323333333337,
 0.08333333333333331, 0.08333323333333337, 0.08333333333333326, 0.08333323333333337, 0.06666666666666671,
 0.09999989999999997], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
