"""Standalone solution generated by the local Agent.

Task: A
Strategy: hexagonal_or_staggered_initialization
Estimated sum_radii: 1.953935826303
Estimated score denominator: 2.365840
Diagnostics: {'source': 'staggered rows plus fixed-center LP', 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 1.9539358263034106, 'score_estimate': 0.8258951688632412, 'boundary_margin': 1.0000000000287557e-07, 'overlap_margin': 1.0000000000287557e-07}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 1.1000000000000001
HEIGHT = 0.89999999999999991
CENTERS = np.array([[0.11000000000000001, 0.09               ],
 [0.33000000000000007, 0.09               ],
 [0.55               , 0.09               ],
 [0.7700000000000001 , 0.09               ],
 [0.9900000000000001 , 0.09               ],
 [0.20625000000000002, 0.26999999999999996],
 [0.48125000000000007, 0.26999999999999996],
 [0.7562500000000002 , 0.26999999999999996],
 [0.9625000000000001 , 0.26999999999999996],
 [0.1375             , 0.45               ],
 [0.4125000000000001 , 0.45               ],
 [0.6875000000000002 , 0.45               ],
 [0.9625000000000001 , 0.45               ],
 [0.20625000000000002, 0.6299999999999999 ],
 [0.48125000000000007, 0.6299999999999999 ],
 [0.7562500000000002 , 0.6299999999999999 ],
 [0.9625000000000001 , 0.6299999999999999 ],
 [0.1375             , 0.8099999999999999 ],
 [0.4125000000000001 , 0.8099999999999999 ],
 [0.6875000000000002 , 0.8099999999999999 ],
 [0.9625000000000001 , 0.8099999999999999 ]], dtype=float)
RADII = np.array([0.0899999          , 0.0899999          , 0.0899999          , 0.0899999          , 0.0899999          ,
 0.11411776625271988, 0.10268254331931573, 0.09052440970683157, 0.09000000000000025, 0.07856467706659595,
 0.08999990000000008, 0.10215803361248424, 0.0899998999999998 , 0.11411776625271972, 0.10268254331931556,
 0.0905244097068314 , 0.09000000000000008, 0.07856467706659612, 0.08999989999999997, 0.08999989999999997,
 0.08999989999999997], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
