"""Standalone solution generated by the local Agent.

Task: A
Strategy: self_evolve_solver_switch
Estimated sum_radii: 2.365825687226
Estimated score denominator: 2.365840
Diagnostics: {'candidate_metadata': {'strategy_family': 'solver_switch', 'solver': 'lp_zero_margin'}, 'operator_context': {'task': 'A', 'operator': 'solver_switch', 'generation': 5, 'batch_index': 3, 'seed': 5199, 'sigma': 1e-06, 'width_sigma': 1e-06, 'lp_margin': 1e-10, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 1e-07, 'contact_scale': 0.5, 'solver': 'lp_zero_margin', 'solver_switch_jitter': 5e-07, 'target_delta': 3e-07, 'width_direction': 1.0, 'use_llm': False}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.3658256872263768, 'score_estimate': 0.9999939502360163, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.5288843940196541, 'reasons': {'code_hash_new': False, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 3.466127282358488e-07, 'rmsd_component': 0.028884394019654067, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 0.97673110799686058
HEIGHT = 1.0232688920031394
CENTERS = np.array([[0.8527690073643998 , 0.1239624067841238 ],
 [0.2982032237876869 , 0.731339069326355  ],
 [0.71756275666164   , 0.31452613221691106],
 [0.3858950746675695 , 0.11292199895040127],
 [0.9019894508724575 , 0.31647243622479526],
 [0.3858953602947506 , 0.9103467843565775 ],
 [0.7175622100247547 , 0.7087421601394889 ],
 [0.347819868520481  , 0.5116345783592193 ],
 [0.9019897002164385 , 0.7067968949354441 ],
 [0.6138896602742502 , 0.11508306147600283],
 [0.2982033998237962 , 0.29193041556245963],
 [0.852769888092786  , 0.899307268534461  ],
 [0.49589956317096634, 0.30914444425080756],
 [0.8493315111066223 , 0.51163435299651   ],
 [0.604288945263977  , 0.5116346257818651 ],
 [0.13707123496276588, 0.8861973407641679 ],
 [0.11906287881759453, 0.3925715284138334 ],
 [0.6138897486898758 , 0.9081861182915076 ],
 [0.49589944450203005, 0.7141241963207183 ],
 [0.119063068362148  , 0.6306970241081132 ],
 [0.13707167026388603, 0.1370718576265963 ]], dtype=float)
RADII = np.array([0.1239611780246144 , 0.08641165484315569, 0.10969511564788871, 0.11292158035479338, 0.07474152305138262,
 0.11292141506022561, 0.1096952292028392 , 0.13882371574798272, 0.07474140758042204, 0.11508306127600283,
 0.08641190136330164, 0.1239612197040746 , 0.11203227141772182, 0.1273995966902383 , 0.11764199281098481,
 0.1370712118686786 , 0.1190625317192025 , 0.11508277351163178, 0.11203236352982127, 0.11906294394269723,
 0.13707099987871732], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
