"""Standalone solution generated by the local Agent.

Task: A
Strategy: self_evolve_crossover
Estimated sum_radii: 2.365831987097
Estimated score denominator: 2.365840
Diagnostics: {'candidate_metadata': {'strategy_family': 'crossover', 'mate_available': True}, 'operator_context': {'task': 'A', 'operator': 'crossover', 'generation': 4, 'batch_index': 1, 'seed': 4116, 'sigma': 3e-08, 'width_sigma': 3e-08, 'lp_margin': 0.0, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 5e-08, 'contact_scale': 0.5, 'solver': 'lp_zero_margin', 'solver_switch_jitter': 1.5e-08, 'target_delta': 1e-08, 'width_direction': -1.0, 'use_llm': False, 'mate': {'available': True, 'width': 0.9767311079968606, 'height': 1.0232688920031394, 'centers_shape': [21, 2]}}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.3658319870968545, 'score_estimate': 0.9999966130832408, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.5023145502495916, 'reasons': {'code_hash_new': False, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 2.7774602995099403e-08, 'rmsd_component': 0.0023145502495916168, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 0.97673110799686058
HEIGHT = 1.0232688920031394
CENTERS = np.array([[0.8527695003530471 , 0.12396160893657746],
 [0.2982032330181555 , 0.7313385960844638 ],
 [0.7175624709537844 , 0.31452627290882224],
 [0.38589512165106266, 0.11292169958989277],
 [0.9019896052335883 , 0.3164721445908216 ],
 [0.3858951216519876 , 0.9103472028645789 ],
 [0.7175624709539485 , 0.7087426295454634 ],
 [0.34782095834685095, 0.5116345120211323 ],
 [0.9019896052333363 , 0.7067967578642061 ],
 [0.6138897017520789 , 0.11508312757297356],
 [0.2982032330173235 , 0.29193030636930783],
 [0.8527694769892538 , 0.8993073804328728 ],
 [0.4958995841140848 , 0.30914434162008386],
 [0.8493308287316121 , 0.5116344355509933 ],
 [0.6042884876074794 , 0.5116344512270088 ],
 [0.1370713522101104 , 0.8861976764249604 ],
 [0.119062857486448  , 0.3925715942467869 ],
 [0.6138897017533158 , 0.908185774881584  ],
 [0.49589958411496377, 0.7141245608338158 ],
 [0.11906285748656098, 0.6306973082077687 ],
 [0.13707129745025895, 0.13707129745386096]], dtype=float)
RADII = np.array([0.12396160596248505, 0.08641205888618192, 0.10969589648408902, 0.11292169790363851, 0.07474150167011905,
 0.11292168893856049, 0.10969590354334655, 0.1388251445125405 , 0.0747414886765626 , 0.11508312628966907,
 0.08641206231024133, 0.12396151137026658, 0.1120323125664771 , 0.12740012318061614, 0.11764221774351706,
 0.13707121537817904, 0.119062857286448  , 0.11508311692155539, 0.11203230958591186, 0.1190628506361905 ,
 0.13707129725025896], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
