"""Standalone solution generated by the local Agent.

Task: A
Strategy: self_evolve_depth_refinement
Estimated sum_radii: 2.365831917286
Estimated score denominator: 2.365840
Diagnostics: {'candidate_metadata': {'strategy_family': 'depth_refinement', 'target_delta': 1e-07}, 'operator_context': {'task': 'A', 'operator': 'depth_refinement', 'generation': 2, 'batch_index': 0, 'seed': 2061, 'sigma': 1e-06, 'width_sigma': 1e-06, 'lp_margin': 3e-11, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 1e-08, 'contact_scale': 0.5, 'solver': 'lp_zero_margin', 'solver_switch_jitter': 5e-07, 'target_delta': 1e-07, 'width_direction': 1.0, 'use_llm': False}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.3658319172858198, 'score_estimate': 0.9999965835753135, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.5001809801386473, 'reasons': {'code_hash_new': False, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 2.171761663767328e-09, 'rmsd_component': 0.00018098013864727733, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 0.97673120799686053
HEIGHT = 1.0232687920031394
CENTERS = np.array([[0.8527695032682787 , 0.12396160583519476],
 [0.2982032314968569 , 0.731338597842097  ],
 [0.7175624727873597 , 0.3145262713319569 ],
 [0.3858951208312992 , 0.1129216964001908 ],
 [0.9019896085425807 , 0.3164721430295232 ],
 [0.38589512083222416, 0.910347206054281  ],
 [0.7175624727875238 , 0.7087426311223288 ],
 [0.3478210235856938 , 0.5116344512270058 ],
 [0.9019896085423287 , 0.7067967594255047 ],
 [0.6138897027562721 , 0.11508312440056304],
 [0.2982032314960249 , 0.29193030461167474],
 [0.8527695032688728 , 0.899307296619899  ],
 [0.49589958417435703, 0.30914434000016305],
 [0.8493309202435488 , 0.5116344512273688 ],
 [0.6042884885348629 , 0.5116344512270088 ],
 [0.13707129464025888, 0.886197607997398  ],
 [0.11906285453202643, 0.3925715932942841 ],
 [0.6138897027575091 , 0.9081857780539948 ],
 [0.495899584175236  , 0.7141245624537367 ],
 [0.11906285453213943, 0.6306973091602717 ],
 [0.1370712946399049 , 0.13707129445735577]], dtype=float)
RADII = np.array([0.12396160563519476, 0.0864120662020548 , 0.10969590139951665, 0.1129216962001908 , 0.07474149885632729,
 0.11292158574885837, 0.10969590159215634, 0.13882522476358794, 0.07474149885654181, 0.11508312420056303,
 0.08641206398411137, 0.1239614951832403 , 0.1120323130737862 , 0.12740019316657308, 0.1176422383421128 ,
 0.13707118380574138, 0.11906285433202643, 0.11508301374914455, 0.11203230960459655, 0.11906285433213942,
 0.13707129425735579], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
