"""Standalone solution generated by the local Agent.

Task: A
Strategy: self_evolve_solver_switch
Estimated sum_radii: 2.365772540666
Estimated score denominator: 2.365840
Diagnostics: {'candidate_metadata': {'strategy_family': 'solver_switch', 'solver': 'lp'}, 'operator_context': {'task': 'A', 'operator': 'solver_switch', 'generation': 4, 'batch_index': 2, 'seed': 4153, 'sigma': 1e-05, 'width_sigma': 1e-05, 'lp_margin': 1e-11, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 1e-08, 'contact_scale': 0.2, 'solver': 'lp', 'solver_switch_jitter': 5e-06, 'target_delta': 3e-08, 'width_direction': 1.0, 'use_llm': False}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.3657725406662475, 'score_estimate': 0.9999714860963749, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.75, 'reasons': {'code_hash_new': False, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 3.5887546172458334e-06, 'rmsd_component': 0.25, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 0.97673110799686058
HEIGHT = 1.0232688920031394
CENTERS = np.array([[0.8527762848086329 , 0.12395772711602059],
 [0.298207372632593  , 0.7313332017441169 ],
 [0.7175608364159685 , 0.31452828802395616],
 [0.38589603353027274, 0.1129173901008652 ],
 [0.9019902104806998 , 0.3164720445921108 ],
 [0.38589286806410955, 0.9103518167222965 ],
 [0.7175623398643899 , 0.7087443378029962 ],
 [0.3478270545465352 , 0.5116321120160844 ],
 [0.9019862589779287 , 0.7067987452099536 ],
 [0.6138943458574255 , 0.11507079671919086],
 [0.2982010771363351 , 0.2919320407902522 ],
 [0.852771008787044  , 0.8993068147810215 ],
 [0.4958970398679225 , 0.30914355275975125],
 [0.8493312543935106 , 0.5116361827005412 ],
 [0.6042915550646969 , 0.511633847067814  ],
 [0.13706706419828296, 0.8862031906414798 ],
 [0.11905901456014581, 0.39257298839213683],
 [0.61388691298515   , 0.9081867347060459 ],
 [0.4958991010693363 , 0.7141205359162994 ],
 [0.11906458028394958, 0.6306981521814395 ],
 [0.13706817644633137, 0.13706773983573248]], dtype=float)
RADII = np.array([0.1239548229882277 , 0.08640939183162563, 0.10969367897455481, 0.1129173899008652 , 0.07474089731616075,
 0.11291707508084294, 0.10969648038452333, 0.13882128708078775, 0.07473770082373739, 0.11507079651919086,
 0.08641383186317697, 0.12396009900981654, 0.11202993786837165, 0.12739985340334994, 0.11763984563827443,
 0.13706570116165964, 0.1190590143601458 , 0.11508215709709348, 0.11203025964416014, 0.11906458008394957,
 0.1370677396357325 ], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
