"""Standalone solution generated by the local Agent.

Task: A
Strategy: self_evolve_program_patch
Estimated sum_radii: 2.365814261968
Estimated score denominator: 2.365840
Diagnostics: {'candidate_metadata': {'strategy_family': 'program_patch_fallback', 'llm_used': False, 'sigma': 3e-06}, 'operator_context': {'task': 'A', 'operator': 'program_patch', 'generation': 1, 'batch_index': 0, 'seed': 1052, 'sigma': 3e-06, 'width_sigma': 3e-06, 'lp_margin': 1e-11, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 5e-08, 'contact_scale': 0.35, 'solver': 'lp_safe', 'solver_switch_jitter': 1.5e-06, 'target_delta': 3e-08, 'width_direction': -1.0, 'use_llm': False}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.365814261967677, 'score_estimate': 0.9999891209750774, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.45206207261616704, 'reasons': {'code_hash_new': False, 'contact_graph_hash_new': True, 'boundary_pattern_new': False, 'centers_rmsd': 1.224744871394004e-06, 'rmsd_component': 0.10206207261616701, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 0.97673110799686058
HEIGHT = 1.0232688920031394
CENTERS = np.array([[0.8527720316188    , 0.12395999875255954],
 [0.2982032300491913 , 0.7313385995146584 ],
 [0.7175624658266239 , 0.3145262773181541 ],
 [0.38589511973009605, 0.11292169211540619],
 [0.9019896041816098 , 0.3164721450871819 ],
 [0.3858951222953116 , 0.9103472003614035 ],
 [0.7175624733256597 , 0.708742631585123  ],
 [0.3478188108268508 , 0.5116364776978887 ],
 [0.90198960175065   , 0.7067967562209528 ],
 [0.6138897024982225 , 0.11508312521578395],
 [0.29820323627190193, 0.2919303101294868 ],
 [0.8527687247581593 , 0.8993101940866205 ],
 [0.495899584122006  , 0.30914434140718733],
 [0.8493279635867096 , 0.5116339286815177 ],
 [0.6042884852688499 , 0.5116344512270087 ],
 [0.1370731202843514 , 0.8861999884504489 ],
 [0.1190614766988216 , 0.39256893252484093],
 [0.6138896997489319 , 0.9081857685494071 ],
 [0.4958995837756232 , 0.7141245517134506 ],
 [0.11906284635473037, 0.6306973117966611 ],
 [0.13707156116136082, 0.13706831046964607]], dtype=float)
RADII = np.array([0.12395907617806058, 0.08641205083418316, 0.10969589946663627, 0.11292169191540619, 0.0747415036152508 ,
 0.11292168950823664, 0.10969588727804402, 0.13882231775141984, 0.07474150604621056, 0.11508312501578395,
 0.0864120775142598 , 0.12395869771651892, 0.1120322944057351 , 0.1273972444394269 , 0.11764222375171586,
 0.13706890335269054, 0.1190614764988216 , 0.11508312325373228, 0.11203231700116763, 0.11906284615473037,
 0.13706831026964608], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
