"""Standalone solution generated by the local Agent.

Task: A
Strategy: self_evolve_parameter_mutation
Estimated sum_radii: 2.365659697464
Estimated score denominator: 2.365840
Diagnostics: {'candidate_metadata': {'strategy_family': 'parameter_mutation', 'sigma': 1e-05, 'width_sigma': 1e-05}, 'operator_context': {'task': 'A', 'operator': 'parameter_mutation', 'generation': 0, 'batch_index': 0, 'seed': 43, 'sigma': 1e-05, 'width_sigma': 1e-05, 'lp_margin': 0.0, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 1e-07, 'contact_scale': 0.2, 'solver': 'lp', 'solver_switch_jitter': 5e-06, 'target_delta': 1e-08, 'width_direction': 1.0, 'use_llm': False}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.365659697463644, 'score_estimate': 0.9999237892096018, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 1.0, 'reasons': {'code_hash_new': True, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 9.873138914654131e-06, 'rmsd_component': 0.25, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 0.97673953564268068
HEIGHT = 1.0232604643573193
CENTERS = np.array([[0.8527719426481138 , 0.12396839071977825],
 [0.29819737772434196, 0.7313295093532326 ],
 [0.7175425525716732 , 0.3145359891386421 ],
 [0.38589528822406843, 0.11292375690334225],
 [0.9019817692848232 , 0.3164844095711145 ],
 [0.38590455365776444, 0.9103459846257641 ],
 [0.7175569123193695 , 0.7087390626316228 ],
 [0.34781303845462574, 0.5116347168684982 ],
 [0.9019834435561392 , 0.7068026132894115 ],
 [0.6138861070663323 , 0.11507958800233418],
 [0.2982186055473655 , 0.2919230491740823 ],
 [0.8527538211947617 , 0.8993109556704403 ],
 [0.4958788054289707 , 0.30914698540644214],
 [0.8493407345572448 , 0.5116351523776764 ],
 [0.6042885803582224 , 0.5116139451334863 ],
 [0.13707685048746854, 0.8862015679265652 ],
 [0.11905113750886426, 0.39259072595425937],
 [0.6138774615913085 , 0.9081689819779669 ],
 [0.49588147353726464, 0.7141248205428891 ],
 [0.11906623619906247, 0.6307017179468781 ],
 [0.1370679238504768 , 0.1370631707036406 ]], dtype=float)
RADII = np.array([0.12396759279456683, 0.08640402104936945, 0.10965849636738652, 0.11292375670334225, 0.0747382814092705 ,
 0.11290671847172754, 0.10968286503312184, 0.13882367595597792, 0.07475383192902693, 0.11507725424374313,
 0.08638869606368178, 0.12394950848687904, 0.11202052377554049, 0.1273876468490621 , 0.11764346770312051,
 0.1370588962307541 , 0.11905113730886425, 0.11507658353569282, 0.1120273347331276 , 0.11905623831574806,
 0.1370631705036406 ], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
