"""Standalone solution generated by the local Agent.

Task: A
Strategy: self_evolve_depth_refinement
Estimated sum_radii: 2.365830094771
Estimated score denominator: 2.365840
Diagnostics: {'candidate_metadata': {'strategy_family': 'depth_refinement', 'target_delta': 1e-07}, 'operator_context': {'task': 'A', 'operator': 'depth_refinement', 'generation': 1, 'batch_index': 1, 'seed': 1089, 'sigma': 1e-06, 'width_sigma': 1e-06, 'lp_margin': 3e-11, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 1e-08, 'contact_scale': 0.5, 'solver': 'lp_zero_margin', 'solver_switch_jitter': 5e-07, 'target_delta': 1e-07, 'width_direction': 1.0, 'use_llm': False}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.3658300947712845, 'score_estimate': 0.9999958132296709, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.7501809801600745, 'reasons': {'code_hash_new': True, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 2.1717619208941647e-09, 'rmsd_component': 0.00018098016007451372, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 0.97673120799686053
HEIGHT = 1.0232687920031394
CENTERS = np.array([[0.8527697563948692 , 0.12396144481677769],
 [0.2982032314968569 , 0.731338597842097  ],
 [0.7175624727873597 , 0.3145262713319569 ],
 [0.3858951208312992 , 0.1129216964001908 ],
 [0.9019896085425807 , 0.3164721430295232 ],
 [0.38589512083222416, 0.910347206054281  ],
 [0.7175624727875238 , 0.7087426311223288 ],
 [0.3478208023750286 , 0.5116346538740958 ],
 [0.9019896085423287 , 0.7067967594255047 ],
 [0.6138897027562721 , 0.11508312440056304],
 [0.2982032314960249 , 0.29193030461167474],
 [0.8527694253875807 , 0.8993075863344236 ],
 [0.49589958417435703, 0.30914434000016305],
 [0.8493306248295008 , 0.5116343989727834 ],
 [0.6042884885348629 , 0.5116344512270088 ],
 [0.13707147717191864, 0.8861978460776253 ],
 [0.1190627162599179 , 0.3925713270597532 ],
 [0.6138897027575091 , 0.9081857780539948 ],
 [0.495899584175236  , 0.7141245624537367 ],
 [0.11906285453213943, 0.6306973091602717 ],
 [0.13707132086762253, 0.13707099560604113]], dtype=float)
RADII = np.array([0.12396144461677769, 0.08641208905775395, 0.10969580136111362, 0.1129216962001908 , 0.07474159925427983,
 0.11292158574885837, 0.1096959031466552 , 0.13882493992708267, 0.07474145819545247, 0.11508312420056303,
 0.08641206702058742, 0.12396120546871571, 0.11203231006602561, 0.12739985707243692, 0.1176422370744319 ,
 0.13707094572551407, 0.1190627160599179 , 0.11508301374914455, 0.11203227249330427, 0.11906283292643761,
 0.13707099540604115], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
