"""Standalone solution generated by the local Agent.

Task: B
Strategy: self_evolve_crossover
Estimated sum_radii: 2.635935124390
Estimated score denominator: 2.635990
Diagnostics: {'candidate_metadata': {'strategy_family': 'crossover', 'mate_available': True}, 'operator_context': {'task': 'B', 'operator': 'crossover', 'generation': 3, 'batch_index': 0, 'seed': 3071, 'sigma': 3e-07, 'width_sigma': 3e-07, 'lp_margin': 1e-10, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 5e-09, 'contact_scale': 0.2, 'solver': 'lp', 'solver_switch_jitter': 1.5e-07, 'target_delta': 3e-07, 'width_direction': -1.0, 'use_llm': False, 'mate': {'available': True, 'width': None, 'height': None, 'centers_shape': [26, 2]}}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.635935124389565, 'score_estimate': 0.9999791821628932, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.5438458344032967, 'reasons': {'code_hash_new': False, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 5.261500128395605e-07, 'rmsd_component': 0.04384583440329671, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.09615219346990643, 0.6820829779683517 ],
 [0.7283686325498878 , 0.5976351308372921 ],
 [0.6868816313770707 , 0.9076103555363125 ],
 [0.9153573534242331 , 0.08464074393956568],
 [0.7052517264978196 , 0.38692498238118356],
 [0.5013327334451847 , 0.5299645119185622 ],
 [0.27309024118192504, 0.5960447615664494 ],
 [0.3140568122911867 , 0.9074075634804519 ],
 [0.4047833583257885 , 0.7420505830842606 ],
 [0.8932061272198553 , 0.27478371637407867],
 [0.7602859655592665 , 0.7636713397930794 ],
 [0.08492397190365836, 0.0849242635003711 ],
 [0.8892249412411848 , 0.8892235829673737 ],
 [0.9042678286059451 , 0.683259227519547  ],
 [0.2973896446372544 , 0.3816665488705169 ],
 [0.5027166826104521 , 0.07885872214162948],
 [0.8969429630537533 , 0.484597838862555  ],
 [0.24064939141930192, 0.762958649091706  ],
 [0.5044659249062053 , 0.27534060047705267],
 [0.5005727932048734 , 0.9060698540502852 ],
 [0.7053898195823701 , 0.13021837659306448],
 [0.29769196329650843, 0.13326153123467951],
 [0.1111548206062649 , 0.8888487708990388 ],
 [0.10346905044168041, 0.48259625166579256],
 [0.5966422631463393 , 0.7424165315977481 ],
 [0.10518475724051365, 0.2739542047741553 ]], dtype=float)
RADII = np.array([0.09615135997102599, 0.09989795660025258, 0.09238964426368747, 0.08463893485070122, 0.11207647087334002,
 0.13700837940511681, 0.1005963142759196 , 0.09259243631954807, 0.09601636822067545, 0.10678997287229115,
 0.06917817640144776, 0.08492397170365835, 0.11077505855881521, 0.09573217119405487, 0.11514663130438982,
 0.07885872194162948, 0.10305703674624668, 0.06943885153047417, 0.11763094258504184, 0.0939255623968263 ,
 0.1302183763930645 , 0.13325136650867356, 0.1111512289009612 , 0.10346718723397283, 0.09584008969301744,
 0.10518191364473238], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
