"""Standalone solution generated by the local Agent.

Task: B
Strategy: self_evolve_parameter_mutation
Estimated sum_radii: 2.635960976418
Estimated score denominator: 2.635990
Diagnostics: {'candidate_metadata': {'strategy_family': 'parameter_mutation', 'sigma': 1e-06}, 'operator_context': {'task': 'B', 'operator': 'parameter_mutation', 'generation': 0, 'batch_index': 2, 'seed': 118, 'sigma': 1e-06, 'width_sigma': 1e-06, 'lp_margin': 3e-11, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 1e-08, 'contact_scale': 0.5, 'solver': 'lp_zero_margin', 'solver_switch_jitter': 5e-07, 'target_delta': 1e-07, 'width_direction': 1.0, 'use_llm': False}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.63596097641802, 'score_estimate': 0.9999889894946566, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.8415489302406908, 'reasons': {'code_hash_new': True, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 1.0985871628882887e-06, 'rmsd_component': 0.09154893024069072, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.09615080306212968, 0.6820805228933361 ],
 [0.7283702640182633 , 0.5976327966311441 ],
 [0.6868845539017593 , 0.9076082126971647 ],
 [0.915359980910163  , 0.08463981632408232],
 [0.705254758492886  , 0.38692352193407037],
 [0.5013305148592058 , 0.5299628710824124 ],
 [0.2730947003019329 , 0.5960433210091447 ],
 [0.3140560423044122 , 0.907406640790536  ],
 [0.404780217260113  , 0.7420508144510393 ],
 [0.8932114631546975 , 0.27478372154074   ],
 [0.7602877675460664 , 0.7636749350326757 ],
 [0.08492726054719864, 0.08492632028169368],
 [0.8892199939738483 , 0.8892211117168926 ],
 [0.9042688073743088 , 0.6832594087711453 ],
 [0.2973906305473983 , 0.38166591634867114],
 [0.5027144308621248 , 0.07885936158503135],
 [0.8969392985104373 , 0.4846027016668    ],
 [0.24064847762885347, 0.7629595780795203 ],
 [0.5044690395533554 , 0.27534443468769515],
 [0.5005719348765171 , 0.9060741255331308 ],
 [0.7053892843033848 , 0.1302217778590545 ],
 [0.2976902893207512 , 0.1332597881327718 ],
 [0.11115890361205953, 0.8888435375867924 ],
 [0.10346752494378936, 0.48259218612252885],
 [0.5966419314100697 , 0.7424173764606192 ],
 [0.10518272124750505, 0.27395160859944956]], dtype=float)
RADII = np.array([0.09615080286212968, 0.09989613171830886, 0.09239116998100322, 0.08463981612408232, 0.11207727446251767,
 0.1370093194133635 , 0.10060005071264527, 0.09258964632812469, 0.0960195398701563 , 0.10678853664530254,
 0.06917869138089995, 0.08492598970216854, 0.11077801002039729, 0.09573119242569118, 0.115148296095518  ,
 0.07885936138503134, 0.10306032092458359, 0.06943862488659422, 0.11762825939007077, 0.09392587426686917,
 0.13022155436066654, 0.13325794741916325, 0.11115489374252067, 0.10346616527534125, 0.09584204493755671,
 0.10518146208731366], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
