"""Standalone solution generated by the local Agent.

Task: B
Strategy: self_evolve_parameter_mutation
Estimated sum_radii: 2.635980666463
Estimated score denominator: 2.635990
Diagnostics: {'candidate_metadata': {'strategy_family': 'parameter_mutation', 'sigma': 1e-07}, 'operator_context': {'task': 'B', 'operator': 'parameter_mutation', 'generation': 2, 'batch_index': 2, 'seed': 2136, 'sigma': 1e-07, 'width_sigma': 1e-07, 'lp_margin': 3e-10, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 1e-07, 'contact_scale': 0.35, 'solver': 'lp_safe', 'solver_switch_jitter': 5e-08, 'target_delta': 1e-06, 'width_direction': 1.0, 'use_llm': False}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.6359806664633973, 'score_estimate': 0.9999964591911947, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.5093993171840089, 'reasons': {'code_hash_new': False, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'centers_rmsd': 1.1279180620810625e-07, 'rmsd_component': 0.009399317184008854, 'strategy_family_repeated': False, 'threshold': 0.25}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.09615133952530905, 0.682080081005707  ],
 [0.7283701769270371 , 0.5976347603096736 ],
 [0.6868841979603153 , 0.907608345277041  ],
 [0.9153605478093468 , 0.08463955199939335],
 [0.7052538781060533 , 0.3869235950012241 ],
 [0.5013319905490177 , 0.5299635735388402 ],
 [0.2730941877426719 , 0.5960426540664324 ],
 [0.3140571662479195 , 0.9074080723083506 ],
 [0.40478027709801007, 0.742049553444694  ],
 [0.8932098498786663 , 0.2747832793827343 ],
 [0.7602895220989395 , 0.7636733550345225 ],
 [0.08492604170141464, 0.08492618793360322],
 [0.8892208905728148 , 0.8892209624581278 ],
 [0.9042675029724911 , 0.6832586311695014 ],
 [0.29739035863548957, 0.3816659907349548 ],
 [0.5027156155051479 , 0.07886032641374037],
 [0.8969395894108585 , 0.4846008660168518 ],
 [0.24064743463518495, 0.7629590453426423 ],
 [0.5044682191312627 , 0.27534271257218895],
 [0.5005716625371656 , 0.906072606982766  ],
 [0.7053905362820269 , 0.13022102097158578],
 [0.297690636066516  , 0.13325878141347208],
 [0.11115594063220559, 0.8888436585013376 ],
 [0.1034670596276103 , 0.48259575514356606],
 [0.5966411506067205 , 0.7424171892948108 ],
 [0.10518261034019431, 0.2739527923793004 ]], dtype=float)
RADII = np.array([0.09615133922530905, 0.09989829221186831, 0.09239141558626937, 0.08463944957387277, 0.11207707977657876,
 0.13701038130277013, 0.10060021341805307, 0.09259192739164937, 0.09601897481334487, 0.10679014689823678,
 0.06918048508029004, 0.08492604140141465, 0.11077903724187224, 0.09573217875049284, 0.11514884815983949,
 0.07886032611374037, 0.10306041028914151, 0.06944011065922656, 0.11762950479574491, 0.09392716118677066,
 0.13022102067158578, 0.133258497163218  , 0.11115594033220559, 0.1034670593276103 , 0.09584225071932809,
 0.10518257437296331], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
