"""Standalone solution generated by the local Agent.

Task: B
Strategy: self_evolve_solver_switch
Estimated sum_radii: 2.635975148936
Estimated score denominator: 2.635990
Diagnostics: {'candidate_metadata': {'task': 'B', 'blocks_used': ['geometry:micro_jitter', 'radius:solver_switch_lp', 'refine:repair_polish', 'safety:shrink'], 'strategy_family': 'micro_jitter_lp', 'operator_name': 'solver_switch', 'parameters': {'solver': 'lp'}}, 'operator_context': {'task': 'B', 'operator': 'solver_switch', 'generation': 7, 'batch_index': 2, 'seed': 7181, 'sigma': 3e-07, 'width_sigma': 3e-07, 'lp_margin': 3e-10, 'safety': 2e-10, 'contact_tolerance': 5e-08, 'contact_threshold': 5e-08, 'contact_scale': 0.2, 'solver': 'lp', 'solver_switch_jitter': 1.5e-07, 'target_delta': 1e-06, 'width_direction': -1.0, 'use_llm': False, 'evolve_blocks_v2': True, 'enable_fast_refine': True, 'max_refine_steps': 6, 'safety_shrink': 1e-10, 'small_circle_count': 3, 'gap_probe_scale': 0.02, 'edge_band': 2e-08, 'aspect_delta': 1e-06, 'parent_sampling_mode': 'exploit', 'parent_program_id': 'B_P_00002'}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.6359751489359695, 'score_estimate': 0.9999943660393132, 'parent_contact_graph_hash': '8dae3c4e6bea6bd1', 'parent_boundary_pattern': 'left:0,11,22,23,25|right:3,9,12,13,16|bottom:3,11,15,20,21|top:2,7,12,19,22', 'centers_rmsd_to_parent': 3.5666302084805215e-07, 'sorted_radii_l2_to_parent': 4.579027641562261e-07, 'stage': 'E1', 'novelty': {'accepted': True, 'score': 0.6178331510424027, 'reasons': {'code_block_novelty': 0.0, 'contact_graph_novelty': 1.0, 'boundary_pattern_novelty': 1.0, 'centers_rmsd_novelty': 0.11888767361601738, 'radius_distribution_novelty': 1.0, 'strategy_family_novelty': 1.0, 'code_hash_new': False, 'contact_graph_hash_new': True, 'boundary_pattern_new': True, 'contact_graph_changed': True, 'boundary_pattern_changed': True, 'centers_rmsd': 3.5666302084805215e-07, 'centers_rmsd_to_parent': 3.5666302084805215e-07, 'sorted_radii_l2_to_parent': 4.579027641562261e-07, 'strategy_family_repeated': False, 'novelty_rejection_reason': 'none', 'threshold': 0.35}, 'threshold': 0.25}}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.09615109384678544, 0.6820800913533156 ],
 [0.72837094477302   , 0.5976345699984869 ],
 [0.6868842676155986 , 0.9076085679328328 ],
 [0.915361055455258  , 0.08463996278458691],
 [0.7052544361982857 , 0.38692412522216907],
 [0.5013320380983045 , 0.5299638026776977 ],
 [0.27309401439938996, 0.5960427745517779 ],
 [0.3140572254092167 , 0.9074086180034967 ],
 [0.40478087307498667, 0.7420499266178511 ],
 [0.8932099359343826 , 0.2747835190541417 ],
 [0.760289463285396  , 0.7636737592420639 ],
 [0.0849257856269791 , 0.08492650004502401],
 [0.889220687564905  , 0.88922072506938   ],
 [0.9042675501145696 , 0.6832586362002206 ],
 [0.29739060102131426, 0.3816656677091314 ],
 [0.5027154177494897 , 0.07886076316619774],
 [0.8969397154019669 , 0.48460080765787605],
 [0.24064754446671757, 0.7629591878455133 ],
 [0.5044681920010106 , 0.2753420303903102 ],
 [0.5005717101743449 , 0.9060726967283995 ],
 [0.7053903304813389 , 0.13022100143964577],
 [0.2976904990001044 , 0.13325919321022842],
 [0.11115579488049608, 0.8888444611375519 ],
 [0.10346742670338797, 0.4825954110169661 ],
 [0.5966412130692618 , 0.7424167931135558 ],
 [0.10518342169389833, 0.27395245536486523]], dtype=float)
RADII = np.array([0.09615109364678544, 0.09989784286985168, 0.09239143176716716, 0.08463894424474197, 0.11207683575789062,
 0.13701068541151895, 0.10060010436960475, 0.0925913816965033 , 0.09601835629169042, 0.10679006376561742,
 0.06918069394524096, 0.0849257853269791 , 0.11077847118585987, 0.09573215576589372, 0.11514888002451075,
 0.07886030888331938, 0.10306028429803307, 0.0694406623185999 , 0.11762877597809585, 0.09392730297160048,
 0.13022100113964577, 0.13325777520583493, 0.11115553856244811, 0.10346724584582971, 0.0958414389916569 ,
 0.10518208867104921], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
