"""Standalone solution generated by the local Agent.

Task: B
Strategy: hexagonal_or_staggered_initialization
Estimated sum_radii: 2.412308962562
Estimated score denominator: 2.635990
Diagnostics: {'source': 'staggered rows plus fixed-center LP', 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.4123089625617653, 'score_estimate': 0.9151434423354281, 'boundary_margin': 1.0000000000287557e-07, 'overlap_margin': 1.0000000000287557e-07}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.08333333333333333, 0.1                ],
 [0.25               , 0.1                ],
 [0.41666666666666663, 0.1                ],
 [0.5833333333333334 , 0.1                ],
 [0.75               , 0.1                ],
 [0.9166666666666666 , 0.1                ],
 [0.15000000000000002, 0.3                ],
 [0.35000000000000003, 0.3                ],
 [0.55               , 0.3                ],
 [0.7500000000000001 , 0.3                ],
 [0.9                , 0.3                ],
 [0.1                , 0.5                ],
 [0.30000000000000004, 0.5                ],
 [0.5                , 0.5                ],
 [0.7000000000000001 , 0.5                ],
 [0.9                , 0.5                ],
 [0.15000000000000002, 0.7                ],
 [0.35000000000000003, 0.7                ],
 [0.55               , 0.7                ],
 [0.7500000000000001 , 0.7                ],
 [0.9                , 0.7                ],
 [0.1                , 0.9                ],
 [0.30000000000000004, 0.9                ],
 [0.5                , 0.9                ],
 [0.7000000000000001 , 0.9                ],
 [0.9                , 0.9                ]], dtype=float)
RADII = np.array([0.08333323333333333, 0.08333333333333336, 0.08333323333333327, 0.08333333333333347, 0.08333323333333316,
 0.08333323333333337, 0.11846584384264919, 0.08153405615735082, 0.11846584384264919, 0.08153405615735088,
 0.06846584384264903, 0.08768933743823387, 0.11231056256176608, 0.08768933743823387, 0.11231056256176619,
 0.08768933743823376, 0.10615528128088311, 0.0938446187191169 , 0.10615528128088311, 0.09384461871911678,
 0.05615528128088312, 0.09999989999999997, 0.09999989999999997, 0.09999989999999997, 0.09999989999999997,
 0.09999989999999997], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
