"""Standalone solution generated by the local Agent.

Task: B
Strategy: multi_start_slsqp
Estimated sum_radii: 2.607923129366
Estimated score denominator: 2.635990
Diagnostics: {'source': 'multi-start SLSQP', 'starts': 8, 'start_details': [{'optimizer': 'SLSQP', 'success': True, 'message': 'Optimization terminated successfully', 'nit': 13, 'maxiter': 360, 'margin': 8e-08, 'seed_offset': 111}, {'optimizer': 'SLSQP', 'success': True, 'message': 'Optimization terminated successfully', 'nit': 9, 'maxiter': 360, 'margin': 8e-08, 'seed_offset': 112}, {'optimizer': 'SLSQP', 'success': True, 'message': 'Optimization terminated successfully', 'nit': 14, 'maxiter': 360, 'margin': 8e-08, 'seed_offset': 113}, {'optimizer': 'SLSQP', 'success': True, 'message': 'Optimization terminated successfully', 'nit': 8, 'maxiter': 360, 'margin': 8e-08, 'seed_offset': 114}, {'optimizer': 'SLSQP', 'success': True, 'message': 'Optimization terminated successfully', 'nit': 11, 'maxiter': 360, 'margin': 8e-08, 'seed_offset': 115}, {'optimizer': 'SLSQP', 'success': True, 'message': 'Optimization terminated successfully', 'nit': 9, 'maxiter': 360, 'margin': 8e-08, 'seed_offset': 116}, {'optimizer': 'SLSQP', 'success': True, 'message': 'Optimization terminated successfully', 'nit': 7, 'maxiter': 360, 'margin': 8e-08, 'seed_offset': 117}, {'optimizer': 'SLSQP', 'success': True, 'message': 'Optimization terminated successfully', 'nit': 8, 'maxiter': 360, 'margin': 8e-08, 'seed_offset': 118}], 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.607923129365936, 'score_estimate': 0.9893524366048188, 'boundary_margin': 7.99999999995249e-08, 'overlap_margin': 7.999567824823473e-08}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.06939098858482   , 0.06939098858481904],
 [0.22729263908783062, 0.08982779037685559],
 [0.4146066849026891 , 0.09764957372509712],
 [0.5996486817292633 , 0.08766185282011835],
 [0.7425846323537052 , 0.0582656784822739 ],
 [0.897297548321335  , 0.10270245167866701],
 [0.10392739984191114, 0.2392334813049801 ],
 [0.30587058550827484, 0.26183337402771645],
 [0.5295712134376178 , 0.2896617620255108 ],
 [0.7332152627822036 , 0.20909443650205367],
 [0.725634579679044  , 0.4012394399213355 ],
 [0.9001969083833007 , 0.3051871582023131 ],
 [0.06170784874185332, 0.39939751777024424],
 [0.19338121521678525, 0.38884548477726744],
 [0.36642678568089365, 0.48226520801958406],
 [0.5712814689245181 , 0.49026635905338134],
 [0.7144296824586871 , 0.605212654309255  ],
 [0.8974198477036228 , 0.5075512680873119 ],
 [0.12940546491778845, 0.5781188115324538 ],
 [0.3157014613929877 , 0.6907257143792047 ],
 [0.5106476565236383 , 0.6670062758165621 ],
 [0.6826599845664073 , 0.8540162937445867 ],
 [0.8938423295361104 , 0.7162583513804327 ],
 [0.9108375698489661 , 0.9108375698489639 ],
 [0.14650303324801803, 0.8534969667519822 ],
 [0.4148195035195998 , 0.8771462786131118 ]], dtype=float)
RADII = np.array([0.06939090858481904, 0.0898277103768556 , 0.09764949372509713, 0.08766177282011835, 0.0582655984822739 ,
 0.10270237167866499, 0.10392731984191114, 0.09927645196156357, 0.12614837818489325, 0.09285380841649223,
 0.09944059693053763, 0.09980301161669931, 0.06170776874185332, 0.07038765019139429, 0.1262642826112596 ,
 0.07874651433118789, 0.1048400659442104 , 0.10258007229637718, 0.12940538491778844, 0.08827896922330865,
 0.1081048369833877 , 0.14598362625541333, 0.10615759046388958, 0.08916235015103387, 0.14650295324801782,
 0.12285364138688822], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
