"""Standalone solution generated by the local Agent.

Task: B
Strategy: contact_graph_feasibility_refine
Estimated sum_radii: 2.593475848617
Estimated score denominator: 2.635990
Diagnostics: {'optimizer': 'fixed_center_lp_jitter', 'success': True, 'message': 'cheap batch neighbor', 'source': 'contact_graph_feasibility_refine', 'strategy_family': 'contact_graph_refinement', 'parent_sum_radii': 2.5934752785935125, 'target_sum_radii': 2.5934753085935123, 'delta': 3e-08, 'parent_contact_graph': {'active_edges': [], 'active_edge_count': 0, 'contact_graph_hash': '4f53cda18c2baa0c', 'active_boundary_pattern': 'none', 'active_boundary_count': 0, 'min_pairwise_margin': 7.999739622122082e-08, 'min_boundary_margin': 7.99999999995249e-08, 'median_pairwise_margin': 0.30568755156999317, 'tolerance': 5e-08}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.5934758486167846, 'score_estimate': 0.9838716568032445, 'contact_graph': {'active_edges': [(0, 1), (0, 6), (1, 2), (1, 6), (1, 7), (2, 7), (3, 7), (4, 5), (4, 10), (5, 10), (6, 7), (6, 12), (7, 8), (7, 13), (7, 14), (9, 10), (9, 11), (10, 11), (11, 17), (12, 13), (12, 18), (15, 20), (15, 22), (17, 22), (17, 23), (18, 24), (18, 25), (19, 20), (19, 25), (20, 21), (20, 22), (20, 25), (21, 22), (21, 23), (21, 25), (22, 23), (24, 25)], 'active_edge_count': 37, 'contact_graph_hash': '5379405974a3bc84', 'active_boundary_pattern': 'left:12,24|right:5,23|bottom:0,2,5|top:21,23,24,25', 'active_boundary_count': 11, 'min_pairwise_margin': 1.9999996103692297e-10, 'min_boundary_margin': 1.560557394419959e-08, 'median_pairwise_margin': 0.3056875189144265, 'tolerance': 5e-08}}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.07394330531490809, 0.07394330084021031],
 [0.23560524496044963, 0.08836028092887702],
 [0.39202248694598907, 0.06922334190251665],
 [0.5871105559807976 , 0.1374514182031244 ],
 [0.7934732063600101 , 0.07745569257489608],
 [0.9351831585708208 , 0.06481684470755984],
 [0.12058441117736787, 0.2627967015535022 ],
 [0.3593628621513683 , 0.25393988520489785],
 [0.530957024349449  , 0.3417000983050478 ],
 [0.7146904060600964 , 0.34889300663506057],
 [0.8943006437656119 , 0.23035948185901248],
 [0.9032092645358323 , 0.432653433261494  ],
 [0.07444184580171317, 0.4522856992943354 ],
 [0.24885367545295384, 0.4425495566419474 ],
 [0.4188316671312326 , 0.4326874752382917 ],
 [0.577014220864346  , 0.521829726458224  ],
 [0.7611644526699657 , 0.5249906169169056 ],
 [0.8990893695321887 , 0.63031178702822   ],
 [0.13971798039618827, 0.6562548738588788 ],
 [0.37692392284970455, 0.6013421939429998 ],
 [0.5274856815912453 , 0.7071120731157334 ],
 [0.6132332062646694 , 0.8838228941253626 ],
 [0.7068580422529733 , 0.6889117587392608 ],
 [0.8643272671132779 , 0.8643272729478476 ],
 [0.10337927931507707, 0.8966207304287687 ],
 [0.3508701394241262 , 0.8518761115419274 ]], dtype=float)
RADII = np.array([0.07394325252873299, 0.08836022397234401, 0.06922329513281189, 0.13745133821348826, 0.07745562738996911,
 0.06481679813257776, 0.1205843568466959 , 0.11835828390077995, 0.07437573398505866, 0.10949831882649319,
 0.1056992986830979 , 0.09679068249471844, 0.07444181348756686, 0.10024152145470605, 0.07002224865260398,
 0.11154877008050965, 0.07262850507534946, 0.10091057122344226, 0.13971792165376162, 0.10376109019560129,
 0.08023916585463958, 0.1161770617185519 , 0.10005417802093226, 0.13567269636736767, 0.10337925396565739,
 0.14812384075932677], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
