"""Standalone solution generated by the local Agent.

Task: B
Strategy: contact_graph_feasibility_refine
Estimated sum_radii: 2.635895103452
Estimated score denominator: 2.635990
Diagnostics: {'optimizer': 'fixed_center_lp_jitter', 'success': True, 'message': 'cheap batch neighbor', 'source': 'contact_graph_feasibility_refine', 'strategy_family': 'contact_graph_refinement', 'parent_sum_radii': 2.6358944876583728, 'target_sum_radii': 2.6358944976583727, 'delta': 1e-08, 'parent_contact_graph': {'active_edges': [], 'active_edge_count': 0, 'contact_graph_hash': '4f53cda18c2baa0c', 'active_boundary_pattern': 'none', 'active_boundary_count': 0, 'min_pairwise_margin': 7.999919554579904e-08, 'min_boundary_margin': 7.99999999995249e-08, 'median_pairwise_margin': 0.32782000225949715, 'tolerance': 5e-08}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.635895103452235, 'score_estimate': 0.9999639996556264, 'contact_graph': {'active_edges': [(0, 6), (0, 23), (1, 13), (1, 16), (1, 24), (2, 12), (2, 19), (2, 24), (3, 9), (3, 20), (4, 5), (4, 9), (4, 16), (4, 20), (5, 6), (5, 8), (5, 24), (6, 8), (6, 23), (7, 8), (7, 19), (7, 22), (8, 19), (8, 24), (9, 16), (9, 20), (10, 13), (10, 24), (11, 21), (11, 25), (12, 13), (13, 16), (14, 23), (14, 25), (15, 18), (15, 20), (15, 21), (17, 22), (19, 24), (21, 25), (23, 25)], 'active_edge_count': 41, 'contact_graph_hash': '332a627fe8731bab', 'active_boundary_pattern': 'left:22,23,25|right:13,16|bottom:15|top:22', 'active_boundary_count': 7, 'min_pairwise_margin': 1.9999997491471078e-10, 'min_boundary_margin': 1.8260527839819574e-08, 'median_pairwise_margin': 0.3278199712033191, 'tolerance': 5e-08}}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.09286078087294795, 0.6719432691488451 ],
 [0.7264795477712024 , 0.5943762165317986 ],
 [0.6845402303231958 , 0.9068948197020652 ],
 [0.9153962758381924 , 0.08460372404587438],
 [0.703277256415649  , 0.38002605687086943],
 [0.4979367654702691 , 0.5266850551341637 ],
 [0.2689401132244961 , 0.5919024266306033 ],
 [0.3089916143142017 , 0.9068749124373345 ],
 [0.3999532536019282 , 0.7398509705287358 ],
 [0.8951169977484276 , 0.2730020785850443 ],
 [0.7585496236870081 , 0.7618633093040368 ],
 [0.08413604110594625, 0.08413604384701877],
 [0.8884042491903784 , 0.8884042470547798 ],
 [0.9036247317303643 , 0.6809910166655626 ],
 [0.2942878923868225 , 0.3785847256663984 ],
 [0.49911584190972275, 0.07878377156205846],
 [0.896569754672662  , 0.4813101796229938 ],
 [0.232020620874549  , 0.760617253571528  ],
 [0.49885771174970517, 0.2733543750827652 ],
 [0.49677595938825475, 0.9053343403025748 ],
 [0.7035478451929646 , 0.13261765854265356],
 [0.29503511344398803, 0.13216230051810812],
 [0.10821649053883614, 0.8917835080119928 ],
 [0.10195009448102846, 0.4773446294360129 ],
 [0.5936185060462216 , 0.7403928752445726 ],
 [0.10409761429773531, 0.27130819222269986]], dtype=float)
RADII = np.array([0.09286072171089849, 0.10081129854420759, 0.09310510863528693, 0.0846036720567592 , 0.11479091133536855,
 0.13754529204912744, 0.10055710108931326, 0.09312503048256308, 0.09706172541168419, 0.10488294914425948,
 0.0697184242367159 , 0.08413598746061762, 0.111595700686692  , 0.09637522564177807, 0.11426125373139445,
 0.07878374632176433, 0.1034302029716194 , 0.07214993569620524, 0.11578699570990181, 0.09466560495733863,
 0.13261759882620477, 0.13216224439680413, 0.1082164722783083 , 0.10195005839164731, 0.09660427155794714,
 0.10409757012782775], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
