"""Standalone solution generated by the local Agent.

Task: B
Strategy: contact_graph_feasibility_refine
Estimated sum_radii: 2.593475935129
Estimated score denominator: 2.635990
Diagnostics: {'optimizer': 'fixed_center_lp_jitter', 'success': True, 'message': 'cheap batch neighbor', 'source': 'contact_graph_feasibility_refine', 'strategy_family': 'contact_graph_refinement', 'parent_sum_radii': 2.5934758909232425, 'target_sum_radii': 2.5934759209232423, 'delta': 3e-08, 'parent_contact_graph': {'active_edges': [(0, 1), (0, 6), (1, 2), (1, 7), (2, 7), (3, 4), (3, 7), (3, 9), (4, 5), (4, 10), (5, 10), (6, 7), (6, 12), (7, 8), (7, 13), (7, 14), (8, 9), (8, 14), (8, 15), (9, 10), (9, 11), (9, 15), (9, 16), (10, 11), (11, 16), (11, 17), (12, 13), (12, 18), (14, 15), (15, 20), (15, 22), (16, 22), (17, 22), (17, 23), (18, 24), (19, 20), (20, 21), (20, 22), (20, 25), (21, 22), (21, 23), (21, 25), (22, 23), (24, 25)], 'active_edge_count': 44, 'contact_graph_hash': 'bd8bbcd00d2f680a', 'active_boundary_pattern': 'left:0,12,24|right:5,10,11,23|bottom:2,5|top:21,23,24', 'active_boundary_count': 12, 'min_pairwise_margin': 1.9999998879249858e-10, 'min_boundary_margin': 2.0947473602928035e-08, 'median_pairwise_margin': 0.30568752306457825, 'tolerance': 5e-08}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.5934759351293466, 'score_estimate': 0.9838716896230056, 'contact_graph': {'active_edges': [(0, 6), (1, 2), (2, 3), (2, 7), (3, 4), (3, 8), (4, 5), (4, 10), (5, 10), (6, 7), (6, 13), (7, 8), (7, 14), (8, 9), (8, 14), (8, 15), (10, 11), (11, 16), (11, 17), (13, 18), (14, 15), (14, 19), (15, 16), (15, 19), (15, 20), (15, 22), (16, 17), (16, 22), (17, 22), (17, 23), (18, 19), (18, 24), (18, 25), (19, 20), (19, 25), (20, 21), (20, 22), (20, 25), (21, 22), (21, 23), (21, 25), (22, 23), (24, 25)], 'active_edge_count': 43, 'contact_graph_hash': '04120fc55d4d0b07', 'active_boundary_pattern': 'left:6,24|right:5,11,17,23|bottom:2,5|top:21,23,24', 'active_boundary_count': 11, 'min_pairwise_margin': 1.9999998879249858e-10, 'min_boundary_margin': 1.772721150428147e-08, 'median_pairwise_margin': 0.3056875119946748, 'tolerance': 5e-08}}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.0739433090158361 , 0.07394330606501341],
 [0.2356052512400999 , 0.08836028691914954],
 [0.39202247983627647, 0.06922335108225153],
 [0.5871105635270533 , 0.13745140044515763],
 [0.7934732068469743 , 0.07745569008247048],
 [0.9351831587881274 , 0.06481683702915009],
 [0.12058441363630715, 0.26279671173467517],
 [0.35936286086196473, 0.2539399029352776 ],
 [0.5309570315786715 , 0.34170010123063727],
 [0.7146904116844597 , 0.3488929958963878 ],
 [0.894300646180698  , 0.23035947995516265],
 [0.9032092748448829 , 0.4326534315314579 ],
 [0.07444184912757813, 0.4522857047790593 ],
 [0.24885366999713474, 0.4425495501378389 ],
 [0.41883167227301105, 0.4326874726852148 ],
 [0.5770142250642765 , 0.5218297356991889 ],
 [0.7611644587446844 , 0.5249906118015    ],
 [0.8990893791798962 , 0.6303117882028756 ],
 [0.13971798509853253, 0.656254858708622  ],
 [0.3769239262553199 , 0.6013422021022785 ],
 [0.5274856797126884 , 0.707112085362996  ],
 [0.6132332020302952 , 0.883822897978461  ],
 [0.7068580496802918 , 0.6889117534011848 ],
 [0.8643272748613204 , 0.8643272731422577 ],
 [0.10337928097021172, 0.8966207190516517 ],
 [0.35087014681342316, 0.8518761118687085 ]], dtype=float)
RADII = np.array([0.07394325412599558, 0.08836021404430956, 0.06922331256386018, 0.1374513445294445 , 0.07745562920684397,
 0.06481680013359095, 0.1205843669574914 , 0.11835823609487987, 0.07437578104169451, 0.10949830122643131,
 0.10569930352724592, 0.09679069038630674, 0.07444174426728487, 0.10024153012322916, 0.0700222726359001 ,
 0.11154878858812842, 0.07262854131483985, 0.10091057846370666, 0.1397179301510283 , 0.1037611048870486 ,
 0.0802391647517704 , 0.11617706990255659, 0.10005418098418196, 0.13567269693613399, 0.10337926322113675,
 0.1481238350643061 ], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
