"""Standalone solution generated by the local Agent.

Task: B
Strategy: contact_graph_feasibility_refine
Estimated sum_radii: 2.593475923367
Estimated score denominator: 2.635990
Diagnostics: {'optimizer': 'fixed_center_lp_jitter', 'success': True, 'message': 'cheap batch neighbor', 'source': 'contact_graph_feasibility_refine', 'strategy_family': 'contact_graph_refinement', 'parent_sum_radii': 2.5934758895964785, 'target_sum_radii': 2.5934759195964783, 'delta': 3e-08, 'parent_contact_graph': {'active_edges': [(0, 1), (0, 6), (1, 2), (1, 6), (1, 7), (3, 4), (3, 7), (3, 8), (3, 9), (4, 5), (5, 10), (7, 8), (8, 9), (8, 14), (8, 15), (9, 10), (9, 11), (9, 16), (10, 11), (11, 16), (12, 13), (12, 18), (13, 14), (13, 18), (13, 19), (14, 15), (14, 19), (15, 16), (15, 19), (15, 20), (16, 17), (16, 22), (17, 23), (18, 24), (19, 20), (20, 21), (20, 22), (21, 23), (21, 25), (22, 23)], 'active_edge_count': 40, 'contact_graph_hash': '01d893f596742456', 'active_boundary_pattern': 'left:0,6,24|right:5,23|bottom:0,1,4|top:21,23,24', 'active_boundary_count': 11, 'min_pairwise_margin': 1.9999998879249858e-10, 'min_boundary_margin': 9.070720841108937e-10, 'median_pairwise_margin': 0.30568748952784286, 'tolerance': 5e-08}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.5934759233674822, 'score_estimate': 0.9838716851609765, 'contact_graph': {'active_edges': [(0, 6), (1, 2), (1, 6), (2, 3), (3, 4), (3, 8), (3, 9), (4, 5), (5, 10), (6, 12), (7, 8), (8, 9), (8, 14), (8, 15), (9, 10), (9, 11), (9, 16), (10, 11), (11, 16), (12, 13), (12, 18), (13, 14), (13, 19), (14, 15), (14, 19), (15, 16), (15, 19), (15, 20), (16, 17), (16, 22), (17, 23), (18, 24), (19, 20), (19, 25), (20, 22), (20, 25), (21, 23), (21, 25), (22, 23), (24, 25)], 'active_edge_count': 40, 'contact_graph_hash': '3abcc6c70c3228a1', 'active_boundary_pattern': 'left:0,6,12,24|right:5,23|bottom:0,4|top:23,24,25', 'active_boundary_count': 11, 'min_pairwise_margin': 1.9999998879249858e-10, 'min_boundary_margin': 2.000000026702864e-10, 'median_pairwise_margin': 0.3056874920334419, 'tolerance': 5e-08}}
"""

import numpy as np

EXPECTED_N = 26
CENTERS = np.array([[0.07394330214475721, 0.07394328117814414],
 [0.2356052600671361 , 0.08836027347178012],
 [0.39202247380694377, 0.06922334911833651],
 [0.5871105519783174 , 0.1374514182231104 ],
 [0.7934731924844395 , 0.07745566292660848],
 [0.9351831847517283 , 0.06481687003568581],
 [0.12058440110856469, 0.2627966850380413 ],
 [0.35936287444639287, 0.2539398867812628 ],
 [0.5309570209277618 , 0.3417000994563317 ],
 [0.7146904066760257 , 0.3488929717800279 ],
 [0.8943006269077134 , 0.2303594940004861 ],
 [0.903209237398095  , 0.43265342419855035],
 [0.074441856947213  , 0.45228573457068494],
 [0.2488536732592731 , 0.4425495844252639 ],
 [0.4188316449744206 , 0.43268750255611554],
 [0.5770142019073653 , 0.521829717756466  ],
 [0.7611644437504473 , 0.5249906402580812 ],
 [0.8990893631945228 , 0.6303117927279182 ],
 [0.13971798970254928, 0.656254874547885  ],
 [0.37692392265469493, 0.6013422024581211 ],
 [0.5274856882018917 , 0.707112076493408  ],
 [0.6132331866462616 , 0.8838228986816223 ],
 [0.7068580095487841 , 0.6889117786804195 ],
 [0.8643272677122916 , 0.8643272423176079 ],
 [0.10337926434394767, 0.8966206957484537 ],
 [0.35087015943946365, 0.8518761026670588 ]], dtype=float)
RADII = np.array([0.07394325780639026, 0.08836021333780275, 0.06922329678233428, 0.13745136140814143, 0.07745565197406581,
 0.06481681504827165, 0.1205843756655925 , 0.11835821398062257, 0.07437578297514456, 0.10949832789380326,
 0.10569929394519245, 0.09679067354079426, 0.07444183673665636, 0.1002415173371751 , 0.07002227995125958,
 0.11154876488855511, 0.0726285839368006 , 0.10091052594630395, 0.13971787816058343, 0.10376110509906515,
 0.08023916277286053, 0.11617702542381778, 0.10005413572989781, 0.13567272327289892, 0.10337926414394767,
 0.1481238556095052 ], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        centers, radii = _fallback_grid(int(num_circles), 1.0, 1.0)
        centers, radii = _pair_repair(centers, radii, 1.0, 1.0)
        return centers, radii, float(np.sum(radii))
    centers, radii = _pair_repair(CENTERS, RADII, 1.0, 1.0)
    return centers, radii, float(np.sum(radii))
