"""Standalone solution generated by the local Agent.

Task: A
Strategy: contact_graph_feasibility_refine
Estimated sum_radii: 1.953938229604
Estimated score denominator: 2.365840
Diagnostics: {'optimizer': 'fixed_center_lp_jitter', 'success': True, 'message': 'cheap batch neighbor', 'source': 'contact_graph_feasibility_refine', 'strategy_family': 'contact_graph_refinement', 'parent_sum_radii': 1.9539358263034106, 'target_sum_radii': 1.9539388263034105, 'delta': 3e-06, 'parent_contact_graph': {'active_edges': [], 'active_edge_count': 0, 'contact_graph_hash': '4f53cda18c2baa0c', 'active_boundary_pattern': 'none', 'active_boundary_count': 0, 'min_pairwise_margin': 1.0000000000287557e-07, 'min_boundary_margin': 1.0000000000287557e-07, 'median_pairwise_margin': 0.3453578240404489, 'tolerance': 5e-08}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 1.9539382296041217, 'score_estimate': 0.8258961846972415, 'contact_graph': {'active_edges': [(2, 6), (3, 7), (5, 9), (6, 10), (7, 11), (8, 12), (9, 13), (10, 14), (11, 15), (12, 16), (13, 17), (16, 20)], 'active_edge_count': 12, 'contact_graph_hash': '3b83964c1132d924', 'active_boundary_pattern': 'bottom:0,1,2,3,4|top:17,18,19,20', 'active_boundary_count': 9, 'min_pairwise_margin': 1.9999997491471078e-10, 'min_boundary_margin': 2.000000026702864e-10, 'median_pairwise_margin': 0.35167539877180404, 'tolerance': 5e-08}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 1.1000000000000001
HEIGHT = 0.89999999999999991
CENTERS = np.array([[0.10999991865073284, 0.08999964313355988],
 [0.3300000534111914 , 0.09000009938010443],
 [0.5500004960708045 , 0.08999988019247103],
 [0.7700004910687682 , 0.08999945989979782],
 [0.990000191453006  , 0.08999968670587298],
 [0.20625001179997773, 0.2699996235873757 ],
 [0.4812500142414941 , 0.2699995171836322 ],
 [0.7562502346363005 , 0.2700001531840021 ],
 [0.9625000479943915 , 0.27000043958713765],
 [0.13750026030918064, 0.4500005342417157 ],
 [0.41249935407278315, 0.4500000858916428 ],
 [0.6874997168253887 , 0.4500003970102851 ],
 [0.9624999660834948 , 0.44999968548785296],
 [0.20624978459261975, 0.6299995298310079 ],
 [0.4812501895845577 , 0.6299997762798817 ],
 [0.7562500857256609 , 0.6300004534654882 ],
 [0.9625004187184747 , 0.6299998342526058 ],
 [0.1374999022829846 , 0.8100001125081431 ],
 [0.4124999720105415 , 0.8099997572406522 ],
 [0.6875001855257519 , 0.8100002418677443 ],
 [0.9625001497938616 , 0.810000263314974  ]], dtype=float)
RADII = np.array([0.08999964293355987, 0.09000009918010443, 0.08999987999247103, 0.08999945969979782, 0.08999968650587298,
 0.10268502813656069, 0.10268249582474373, 0.09052566051513868, 0.08999978941295507, 0.08999827697880146,
 0.0900008140715277 , 0.10215729508944649, 0.08999945623777915, 0.10268315810325478, 0.10268173793138699,
 0.09052543239469184, 0.09000069232754275, 0.08999988729185683, 0.0900002425593477 , 0.08999975793225558,
 0.08999973648502592], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
