"""Standalone solution generated by the local Agent.

Task: A
Strategy: contact_graph_feasibility_refine
Estimated sum_radii: 2.365831919962
Estimated score denominator: 2.365840
Diagnostics: {'optimizer': 'fixed_center_lp_jitter', 'success': True, 'message': 'cheap batch neighbor', 'source': 'contact_graph_feasibility_refine', 'strategy_family': 'contact_graph_refinement', 'parent_sum_radii': 2.3658318567655905, 'target_sum_radii': 2.3658318667655904, 'delta': 1e-08, 'parent_contact_graph': {'active_edges': [(0, 2), (0, 4), (0, 9), (1, 18), (1, 19), (2, 9), (2, 12), (2, 13), (2, 14), (3, 9), (3, 12), (3, 20), (4, 13), (5, 15), (5, 17), (5, 18), (6, 8), (6, 13), (7, 10), (7, 14), (7, 18), (7, 19), (8, 11), (8, 13), (9, 12), (10, 12), (10, 16), (10, 20), (11, 17), (12, 14), (13, 14), (14, 18), (15, 19), (16, 19), (16, 20), (17, 18)], 'active_edge_count': 36, 'contact_graph_hash': '9a0d23d264413ee3', 'active_boundary_pattern': 'left:19,20|right:0,8,13|bottom:0,20|top:5,17', 'active_boundary_count': 9, 'min_pairwise_margin': 1.9999997491471078e-10, 'min_boundary_margin': 6.49617049042206e-09, 'median_pairwise_margin': 0.25596973302507864, 'tolerance': 5e-08}, 'internal_valid': True, 'internal_message': 'none', 'sum_radii': 2.365831919961536, 'score_estimate': 0.9999965847062928, 'contact_graph': {'active_edges': [(0, 2), (0, 4), (0, 9), (1, 5), (1, 7), (1, 15), (1, 18), (1, 19), (2, 9), (2, 12), (2, 13), (2, 14), (3, 9), (3, 10), (3, 12), (3, 20), (4, 13), (5, 15), (5, 17), (6, 8), (6, 13), (6, 14), (6, 17), (7, 10), (7, 14), (7, 16), (7, 19), (8, 11), (8, 13), (9, 12), (10, 12), (10, 16), (10, 20), (11, 17), (12, 14), (13, 14), (14, 18), (15, 19), (16, 19), (16, 20)], 'active_edge_count': 40, 'contact_graph_hash': 'df348287e733b2df', 'active_boundary_pattern': 'left:15,19,20|right:0,8,13|bottom:0,20|top:5,15,17', 'active_boundary_count': 11, 'min_pairwise_margin': 1.9999998879249858e-10, 'min_boundary_margin': 8.171306964399605e-09, 'median_pairwise_margin': 0.25596971973331234, 'tolerance': 5e-08}}
"""

import numpy as np

EXPECTED_N = 21

WIDTH = 0.97673110539157315
HEIGHT = 1.0232688946084267
CENTERS = np.array([[0.852769485631639  , 0.12396163567977267],
 [0.2982032647373192 , 0.7313385775893678 ],
 [0.7175624404094247 , 0.31452628305257746],
 [0.38589515447839184, 0.11292173789894218],
 [0.9019895552225464 , 0.31647216341386797],
 [0.38589510907238017, 0.9103471875111607 ],
 [0.7175624624371273 , 0.7087425852870457 ],
 [0.3478210367526915 , 0.5116344501817776 ],
 [0.9019895644044238 , 0.706796741313767  ],
 [0.6138896976855153 , 0.11508316686856865],
 [0.2982032615737963 , 0.29193035198968526],
 [0.8527694637418702 , 0.899307250755741  ],
 [0.49589961593104465, 0.3091443490470479 ],
 [0.8493308992814006 , 0.5116344407065928 ],
 [0.6042884669582175 , 0.5116344439603125 ],
 [0.1370713190296263 , 0.886197575585506  ],
 [0.11906289511549949, 0.39257161935092677],
 [0.6138897071162049 , 0.9081857461940838 ],
 [0.4958995598221472 , 0.7141245301620758 ],
 [0.1190628889073347 , 0.6306973022195709 ],
 [0.1370713381171143 , 0.1370713215782147 ]], dtype=float)
RADII = np.array([0.12396161122065458, 0.08641205277635652, 0.10969585207682381, 0.11292166697855235, 0.07474144848781078,
 0.11292167209592485, 0.10969585857263511, 0.13882518029712498, 0.07474149432063222, 0.11508310350253786,
 0.08641205502895023, 0.12396156099179319, 0.1120322762297109 , 0.1274001849787321 , 0.11764223579350813,
 0.1370712915775343 , 0.11906284276494633, 0.11508313296975006, 0.11203224631209752, 0.11906283957855233,
 0.13707131340690773], dtype=float)
def _pair_repair(centers, radii, width, height):
    safety = 2e-10
    centers = np.asarray(centers, dtype=float).copy()
    radii = np.asarray(radii, dtype=float).copy()
    centers[:, 0] = np.clip(centers[:, 0], safety, width - safety)
    centers[:, 1] = np.clip(centers[:, 1], safety, height - safety)
    limits = np.minimum.reduce([
        centers[:, 0],
        width - centers[:, 0],
        centers[:, 1],
        height - centers[:, 1],
    ])
    radii = np.minimum(np.maximum(radii, 0.0), np.maximum(0.0, limits - safety))
    n = len(radii)
    for _ in range(3):
        changed = False
        for i in range(n):
            for j in range(i + 1, n):
                d = float(np.linalg.norm(centers[i] - centers[j]))
                total = radii[i] + radii[j]
                limit = max(0.0, d - safety)
                if total > limit and total > 0.0:
                    factor = limit / total
                    radii[i] *= factor
                    radii[j] *= factor
                    changed = True
        if not changed:
            break
    return centers, radii


def _fallback_grid(num_circles, width=1.0, height=1.0):
    cols = int(np.ceil(np.sqrt(num_circles * width / max(height, 1e-12))))
    rows = int(np.ceil(num_circles / cols))
    pts = []
    for row in range(rows):
        for col in range(cols):
            if len(pts) >= num_circles:
                break
            pts.append([(col + 0.5) * width / cols, (row + 0.5) * height / rows])
        if len(pts) >= num_circles:
            break
    centers = np.asarray(pts, dtype=float)
    radius = 0.45 * min(width / cols, height / rows)
    radii = np.full(num_circles, radius, dtype=float)
    return centers, radii



def run_packing(num_circles):
    if int(num_circles) != EXPECTED_N:
        width = 1.0
        height = 1.0
        centers, radii = _fallback_grid(int(num_circles), width, height)
        centers, radii = _pair_repair(centers, radii, width, height)
        return centers, radii, float(width), float(height)
    centers, radii = _pair_repair(CENTERS, RADII, WIDTH, HEIGHT)
    return centers, radii, float(WIDTH), float(HEIGHT)
